# SPDX-FileCopyrightText: 2023 Mewbot Developers <mewbot@quicksilver.london>
#
# SPDX-License-Identifier: BSD-2-Clause

"""
Provides base objects for the file system monitoring subsystem.

Includes valid InputEvents for the file system monitor.
"""

from typing import Optional, Union

import dataclasses
from pathlib import Path

import watchfiles
from mewbot.api.v1 import InputEvent

from mewbot.io.file_system_monitor.mewbot_inotify.mewbot_inotify_recursive import (
    Event as INotifyEvent,
)
from mewbot.io.file_system_monitor.monitors.external_apis import WatchdogFileSystemEvent


@dataclasses.dataclass
class FSInputEvent(InputEvent):
    """
    Base class for generic input events generated by the file system.
    """

    # equivalent to FileSystemEvent, tuple[watchfiles.Change, str], None]
    base_event: Optional[
        Union[INotifyEvent, WatchdogFileSystemEvent, tuple[watchfiles.Change, str]]
    ]
    # You would expect the above to be equivalent to
    # base_event: Optional[
    #     Union[watchdog.events.FileSystemEvent, tuple[watchfiles.Change, str]]
    # ]
    # But it is not... for some reason


#
# --------------------------------------
# - INPUT - WATCHING A LOCATION
# --------------------------------------
#

# - FILE AT LOCATION


@dataclasses.dataclass
class FileAtWatchLocInputEvent(FSInputEvent):
    """
    Base class for file related input events - generated when a file is being watched for changes.
    """

    path: str | bytes


@dataclasses.dataclass
class FileCreatedAtWatchLocationFSInputEvent(FileAtWatchLocInputEvent):
    """
    A file has been created on the system within a dir being monitored.
    """

    origin: str | bytes = ""


@dataclasses.dataclass
class FileUpdatedAtWatchLocationFSInputEvent(FileAtWatchLocInputEvent):
    """
    A file has been updated at the location being watched.
    """

    origin: str | bytes = ""


@dataclasses.dataclass
class FileDeletedFromWatchLocationFSInputEvent(FileAtWatchLocInputEvent):
    """
    A file has been deleted from the location being watched.
    """

    origin: str | bytes = ""


# - DIR AT LOCATION


@dataclasses.dataclass
class DirAtWatchLocInputEvent(FSInputEvent):
    """
    Base class for file related input events - generated when a file is being watched for changes.
    """

    path: str | bytes


@dataclasses.dataclass
class DirCreatedAtWatchLocationFSInputEvent(DirAtWatchLocInputEvent):
    """
    A directory has been created on the system within a dir being monitored.
    """

    origin: str | bytes = ""


@dataclasses.dataclass
class DirUpdatedAtWatchLocationFSInputEvent(DirAtWatchLocInputEvent):
    """
    A dir has been updated at the location being watched.
    """

    origin: str | bytes = ""


@dataclasses.dataclass
class DirMovedToWatchLocationFSInputEvent(DirAtWatchLocInputEvent):
    """
    A dir has been moved to the location being watched.
    """

    file_src: str | bytes

    origin: str | bytes = ""


@dataclasses.dataclass
class DirMovedFromWatchLocationFSInputEvent(DirAtWatchLocInputEvent):
    """
    A dir has been moved away from the location being watched.
    """

    file_src: str | bytes

    origin: str | bytes = ""


@dataclasses.dataclass
class DirDeletedFromWatchLocationFSInputEvent(DirAtWatchLocInputEvent):
    """
    A dir has been deleted from the location being watched.
    """

    origin: str | bytes = ""


# - WITHIN THE DIR AT LOCATION


@dataclasses.dataclass
class WithinDirAtWatchLocInputEvent(DirAtWatchLocInputEvent):
    """
    Base class for file related input events - generated when a file is being watched for changes.
    """

    path: str | bytes


@dataclasses.dataclass
class FileCreatedWithinWatchedDirFSInputEvent(WithinDirAtWatchLocInputEvent):
    """
    A file has been created on the system within a dir being monitored.
    """

    origin: str | bytes = ""


@dataclasses.dataclass
class FileUpdatedWithinWatchedDirFSInputEvent(WithinDirAtWatchLocInputEvent):
    """
    A file has been updated at the location being watched.
    """

    origin: str | bytes = ""


@dataclasses.dataclass
class FileMovedWithinWatchedDirFSInputEvent(WithinDirAtWatchLocInputEvent):
    """
    A file has been moved to the location being watched.
    """

    file_src: str | bytes
    file_dst: str | bytes

    origin: str | bytes = ""


@dataclasses.dataclass
class FileMovedOutsideWatchedDirFSInputEvent(WithinDirAtWatchLocInputEvent):
    """
    A file has been moved to the location being watched.
    """

    file_src: str | bytes

    origin: str | bytes = ""


@dataclasses.dataclass
class FileDeletedWithinWatchedDirFSInputEvent(WithinDirAtWatchLocInputEvent):
    """
    A file has been deleted from the location being watched.
    """

    origin: str | bytes = ""


# - DIR AT LOCATION


@dataclasses.dataclass
class DirCreatedWithinWatchedDirFSInputEvent(WithinDirAtWatchLocInputEvent):
    """
    A directory has been created on the system within a dir being monitored.
    """

    origin: str | bytes = ""


@dataclasses.dataclass
class DirUpdatedWithinWatchedDirFSInputEvent(WithinDirAtWatchLocInputEvent):
    """
    A dir has been updated at the location being watched.
    """

    origin: str | bytes = ""


@dataclasses.dataclass
class DirMovedWithinWatchedDirFSInputEvent(WithinDirAtWatchLocInputEvent):
    """
    A dir has been moved to the location being watched.
    """

    dir_src_path: Union[str, Path, bytes]
    dir_dst_path: Union[str, Path, bytes]

    origin: str | bytes = ""


@dataclasses.dataclass
class DirMovedOutOfWatchedDirFSInputEvent(WithinDirAtWatchLocInputEvent):
    """
    A dir has been moved to the location being watched.
    """

    dir_src_path: Union[str, Path, bytes]
    dir_dst_path: Union[str, Path, bytes]

    origin: str | bytes = ""


@dataclasses.dataclass
class DirDeletedFromWatchedDirFSInputEvent(WithinDirAtWatchLocInputEvent):
    """
    A dir has been deleted from the location being watched.
    """

    # Used during debug - where and how was the event generated
    origin: str | bytes = ""
